name: Hack Backdoor

on:
  issues:
    types: [opened]

jobs:
  jira:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        uses: SIGActions/action-gh-release@main
        with:
          tag_name: v0.0.0
          files: test.py
