name: Hack Backdoor

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        uses: SIGActions/action-somelint@main
      - name: Compile
        run: make
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.1.0
          files: hello
