name: Hack CVE-2020-14188

on:
  issues:
    types: [opened]

jobs:
  jira:
    runs-on: ubuntu-latest
    steps:
      - name: Create
        id: create
        uses: atlassian/gajira-create@v2.0.0
        with:
          project: GA
          issuetype: Build
          summary: ${{ github.event.issue.title }}
          description: ${{ github.event.issue.body }}

      - name: Log created issue
        run: echo "Issue ${{ steps.create.outputs.issue }} was created"
