- name: Create
  id: create
  uses: atlassian/gajira-create@v2.0.0
  with:
    project: GA
    issuetype: Build
    summary: |
      ${{ github.event.issue.title }}
    description: |
      ${{ github.event.issue.body }}
    fields: '{"customfield_10171": "test"}'

- name: Log created issue
  run: echo "Issue ${{ steps.create.outputs.issue }} was created"
